apiVersion: v1
kind: Service
metadata: 
  name: fe-kube-service
spec:
  type: LoadBalancer
  ports: 
  - name: frontend
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: angular-frontend
