//Load Data Action Types
export const LOAD_PIECHART_DATA = "LOAD_PIECHART_DATA";
export const LOAD_NAVIGATION_DATA = "LOAD_NAVIGATION_DATA";
export const LOAD_USER_DATA = "LOAD_USER_DATA";
export const LOAD_NOWREADING_DATA = "LOAD_NOWREADING_DATA";
export const LOAD_TABLEROW_DATA = "LOAD_TABLEROW_DATA";
export const LOAD_TABLECOLUMN_DATA = "LOAD_TABLECOLUMN_DATA";

//Success Loading Data Action Types
export const LOAD_PIECHART_DATA_SUCCESS = "LOAD_PIECHART_DATA_SUCCESS";
export const LOAD_NAVIGATION_DATA_SUCCESS = "LOAD_NAVIGATION_DATA_SUCCESS";
export const LOAD_USER_DATA_SUCCESS = "LOAD_USER_DATA_SUCCESS";
export const LOAD_NOWREADING_DATA_SUCCESS = "LOAD_NOWREADING_DATA_SUCCESS";
export const LOAD_TABLEROW_DATA_SUCCESS = "LOAD_TABLEROW_DATA_SUCCESS";
export const LOAD_TABLECOLUMN_DATA_SUCCESS = "LOAD_TABLECOLUMN_DATA_SUCCESS";

//Error Loading Data Action Types
export const LOAD_PIECHART_DATA_ERROR = "LOAD_PIECHART_DATA_ERROR";
export const LOAD_NAVIGATION_DATA_ERROR = "LOAD_NAVIGATION_DATA_ERROR";
export const LOAD_USER_DATA_ERROR = "LOAD_USER_DATA_ERROR";
export const LOAD_NOWREADING_DATA_ERROR = "LOAD_NOWREADING_DATA_ERROR";
export const LOAD_TABLEROW_DATA_ERROR = "LOAD_TABLEROW_DATA_ERROR";
export const LOAD_TABLECOLUMN_DATA_ERROR = "LOAD_TABLECOLUMN_DATA_ERROR";